title: "Shimi's Cyber World"
description: "Cybersecurity insights, tools, and resources by Shimi Cohen"
url: "https://shimicohen1.github.io"
baseurl: "/shimis-cyber-world"
timezone: Asia/Jerusalem

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: /blog/:year/:month/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "page"

exclude:
  - _backup
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
