title: "Shimi's Cyber World"
description: "A cyber ecosystem built around a strong community. Real updates, real discussions, tools, and insights from the field."
url: "https://shimiscyberworld.com"
baseurl: ""
theme: null
markdown: kramdown
timezone: Asia/Jerusalem
permalink: /posts/:title/

collections:
  pages:
    output: true
  tools:
    output: true
    permalink: /tools/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "tools"
    values:
      layout: "tool"
  - scope:
      path: ""
    values:
      layout: "page"

exclude:
  - _backup
  - Gemfile
  - Gemfile.lock
  - vendor

plugins:
  - jekyll-sitemap
